name: apoticare
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.1.3
  flutter_barcode_scanner: ^2.0.0
  geolocator: ^8.2.1
  geocoding: ^2.0.4
  flutter_screenutil: ^5.0.0+2
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  cloud_firestore: ^3.1.17
  sqflite: ^2.0.2+1
  shared_preferences: ^2.0.15
  image_picker: ^0.8.5+3
  firebase_storage: ^10.2.17

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/ilus.png
    - assets/profil.png
    - assets/examples1.png
    - assets/exam2.png
